# Generated by Django 4.2.9 on 2024-09-04 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curriculum",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="description",
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="lessons",
        ),
        migrations.RemoveField(
            model_name="curriculum",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="curriculum",
            name="file",
            field=models.FileField(null=True, upload_to="curriculums/"),
        ),
        migrations.AlterField(
            model_name="curriculum",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
