# Generated by Django 4.2.9 on 2024-09-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_curriculum_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myformmodel",
            name="Title",
            field=models.TextField(default="Untitled Lesson Plan", max_length=100),
        ),
    ]
