# Generated by Django 4.2.9 on 2024-12-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_myformmodel_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myformmodel",
            name="Title",
            field=models.TextField(max_length=100),
        ),
    ]
