# Generated by Django 6.0.4 on 2026-04-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_lessonplan_lesson_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyFormModel',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
