# Generated by Django 4.2.30 on 2026-04-21 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_drop_legacy_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('lesson_assist', 'Lesson Assistance'), ('lesson_review', 'Lesson Review'), ('general_chat', 'General Chat')], default='general_chat', max_length=50)),
                ('prompt_length', models.IntegerField(default=0, help_text='Character count of the prompt')),
                ('used_curriculum_context', models.BooleanField(default=False)),
                ('response_length', models.IntegerField(default=0, help_text='Character count of the response')),
                ('latency_ms', models.IntegerField(default=0, help_text='Time taken in milliseconds')),
                ('success', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
