# Generated by Django 4.2.30 on 2026-04-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_ai_usage_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive this lesson plan'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Save as draft instead of published'),
        ),
    ]
